/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc22;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        //dec2.run("dec2.txt", 1);
        //dec2.run("dec2.txt", 2);
        dec3.run("dec3.txt", 1);
        //dec3.run("dec3.txt", 2);
}
}